=== mahendra-shinde/xml-funda3/xsd-demo2/schema2.xsd
<!-- XML Schema without any namespace -->
<!-- Unique XML Schema which used for defining user-defined schema 
	 Alias "xs" is used for reference to all the element of XML Schema
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="product-list" type="plist"> 
	</xs:element>

	<xs:complexType name="plist">
		<!-- Can use 
			sequence	: all the child elements must follow sequence
			choice		: ONLY ONE child element can be used at a time
			all			: The child elements can be used ONLY ONCE 
							but in any sequence
		 -->
		<xs:sequence>
			<xs:element name="product" minOccurs="2" maxOccurs="10" type="ptype" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ptype">
	<xs:all>
		<xs:element name="id" type="xs:int" />
		<xs:element name="name" type="xs:normalizedString" />
		<xs:element name="price" type="priceType" />
		<xs:element name="quantity" type="xs:int" />
	</xs:all>
	</xs:complexType>

	<xs:simpleType name="priceType">
		<xs:restriction base="xs:float"> 
			<xs:minInclusive value="100" />
			<xs:maxInclusive value="100000" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== mahendra-shinde/xml-funda3/xsd-demo2/data1.xml
<product-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="./schema2.xsd">
	<product>
		<name>Product X</name>
		<id>101</id>
		<price>12000</price>
		<quantity>12</quantity>
	</product>
	<product>
		<id>101</id>
		<price>12000</price>
		<name>Product X</name>
		<quantity>12</quantity>
	</product>		
</product-list>
